language: go

go:
  - 1.13.x

before_install:
  - go get -v golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make lint
  - make race
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile=cover/coverage.cov -service=travis-ci -repotoken $COVERALLS_TOKEN